merchandise = [
    # Demo Artist 1
    {
        "name": "Sticker",
        "price": 1.50,
        "url": "test.url",
        "artist_id": 1,
    },
    {
        "name": "Album 1",
        "price": 9.00,
        "url": "test.url",
        "artist_id": 1,
    },
    {
        "name": "Album 2",
        "price": 10.00,
        "url": "test.url",
        "artist_id": 1,
    },
    {
        "name": "Tank Top 1",
        "price": 18.50,
        "url": "test.url",
        "artist_id": 1,
    },
    {
        "name": "Tank Top 2",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 1,
    },
    {
        "name": "T-Shirt 1",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 1,
    },
    {
        "name": "T-Shirt 2",
        "price": 22.50,
        "url": "test.url",
        "artist_id": 1,
    },
    {
        "name": "Hoodie 1",
        "price": 23.50,
        "url": "test.url",
        "artist_id": 1,
    },
    {
        "name": "Hoodie 2",
        "price": 25.00,
        "url": "test.url",
        "artist_id": 1,
    },
    # Demo Artist 2
    {
        "name": "Sticker",
        "price": 1.50,
        "url": "test.url",
        "artist_id": 2,
    },
    {
        "name": "Album 1",
        "price": 9.00,
        "url": "test.url",
        "artist_id": 2,
    },
    {
        "name": "Album 2",
        "price": 10.00,
        "url": "test.url",
        "artist_id": 2,
    },
    {
        "name": "Tank Top 1",
        "price": 18.50,
        "url": "test.url",
        "artist_id": 2,
    },
    {
        "name": "Tank Top 2",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 2,
    },
    {
        "name": "T-Shirt 1",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 2,
    },
    {
        "name": "T-Shirt 2",
        "price": 22.50,
        "url": "test.url",
        "artist_id": 2,
    },
    {
        "name": "Hoodie 1",
        "price": 23.50,
        "url": "test.url",
        "artist_id": 2,
    },
    {
        "name": "Hoodie 2",
        "price": 25.00,
        "url": "test.url",
        "artist_id": 2,
    },
    # Demo Artist 3
    {
        "name": "Sticker",
        "price": 1.50,
        "url": "test.url",
        "artist_id": 3,
    },
    {
        "name": "Album 1",
        "price": 9.00,
        "url": "test.url",
        "artist_id": 3,
    },
    {
        "name": "Album 2",
        "price": 10.00,
        "url": "test.url",
        "artist_id": 3,
    },
    {
        "name": "Tank Top 1",
        "price": 18.50,
        "url": "test.url",
        "artist_id": 3,
    },
    {
        "name": "Tank Top 2",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 3,
    },
    {
        "name": "T-Shirt 1",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 3,
    },
    {
        "name": "T-Shirt 2",
        "price": 22.50,
        "url": "test.url",
        "artist_id": 3,
    },
    {
        "name": "Hoodie 1",
        "price": 23.50,
        "url": "test.url",
        "artist_id": 3,
    },
    {
        "name": "Hoodie 2",
        "price": 25.00,
        "url": "test.url",
        "artist_id": 3,
    },
    # Demo Artist 6
    {
        "name": "Sticker",
        "price": 1.50,
        "url": "test.url",
        "artist_id": 6,
    },
    {
        "name": "Album 1",
        "price": 9.00,
        "url": "test.url",
        "artist_id": 6,
    },
    {
        "name": "Album 2",
        "price": 10.00,
        "url": "test.url",
        "artist_id": 6,
    },
    {
        "name": "Tank Top 1",
        "price": 18.50,
        "url": "test.url",
        "artist_id": 6,
    },
    {
        "name": "Tank Top 2",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 6,
    },
    {
        "name": "T-Shirt 1",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 6,
    },
    {
        "name": "T-Shirt 2",
        "price": 22.50,
        "url": "test.url",
        "artist_id": 6,
    },
    {
        "name": "Hoodie 1",
        "price": 23.50,
        "url": "test.url",
        "artist_id": 6,
    },
    {
        "name": "Hoodie 2",
        "price": 25.00,
        "url": "test.url",
        "artist_id": 6,
    },
    # Demo Artist 7
    {
        "name": "Sticker",
        "price": 1.50,
        "url": "test.url",
        "artist_id": 7,
    },
    {
        "name": "Album 1",
        "price": 9.00,
        "url": "test.url",
        "artist_id": 7,
    },
    {
        "name": "Album 2",
        "price": 10.00,
        "url": "test.url",
        "artist_id": 7,
    },
    {
        "name": "Tank Top 1",
        "price": 18.50,
        "url": "test.url",
        "artist_id": 7,
    },
    {
        "name": "Tank Top 2",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 7,
    },
    {
        "name": "T-Shirt 1",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 7,
    },
    {
        "name": "T-Shirt 2",
        "price": 22.50,
        "url": "test.url",
        "artist_id": 7,
    },
    {
        "name": "Hoodie 1",
        "price": 23.50,
        "url": "test.url",
        "artist_id": 7,
    },
    {
        "name": "Hoodie 2",
        "price": 25.00,
        "url": "test.url",
        "artist_id": 7,
    },
    # Demo Artist 9
    {
        "name": "Sticker",
        "price": 1.50,
        "url": "test.url",
        "artist_id": 9,
    },
    {
        "name": "Album 1",
        "price": 9.00,
        "url": "test.url",
        "artist_id": 9,
    },
    {
        "name": "Album 2",
        "price": 10.00,
        "url": "test.url",
        "artist_id": 9,
    },
    {
        "name": "Tank Top 1",
        "price": 18.50,
        "url": "test.url",
        "artist_id": 9,
    },
    {
        "name": "Tank Top 2",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 9,
    },
    {
        "name": "T-Shirt 1",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 9,
    },
    {
        "name": "T-Shirt 2",
        "price": 22.50,
        "url": "test.url",
        "artist_id": 9,
    },
    {
        "name": "Hoodie 1",
        "price": 23.50,
        "url": "test.url",
        "artist_id": 9,
    },
    {
        "name": "Hoodie 2",
        "price": 25.00,
        "url": "test.url",
        "artist_id": 9,
    },
    # Demo Artist 10
    {
        "name": "Sticker",
        "price": 1.50,
        "url": "test.url",
        "artist_id": 10,
    },
    {
        "name": "Album 1",
        "price": 9.00,
        "url": "test.url",
        "artist_id": 10,
    },
    {
        "name": "Album 2",
        "price": 10.00,
        "url": "test.url",
        "artist_id": 10,
    },
    {
        "name": "Tank Top 1",
        "price": 18.50,
        "url": "test.url",
        "artist_id": 10,
    },
    {
        "name": "Tank Top 2",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 10,
    },
    {
        "name": "T-Shirt 1",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 10,
    },
    {
        "name": "T-Shirt 2",
        "price": 22.50,
        "url": "test.url",
        "artist_id": 10,
    },
    {
        "name": "Hoodie 1",
        "price": 23.50,
        "url": "test.url",
        "artist_id": 10,
    },
    {
        "name": "Hoodie 2",
        "price": 25.00,
        "url": "test.url",
        "artist_id": 10,
    },
    # Demo Artist 11
    {
        "name": "Sticker",
        "price": 1.50,
        "url": "test.url",
        "artist_id": 11,
    },
    {
        "name": "Album 1",
        "price": 9.00,
        "url": "test.url",
        "artist_id": 11,
    },
    {
        "name": "Album 2",
        "price": 10.00,
        "url": "test.url",
        "artist_id": 11,
    },
    {
        "name": "Tank Top 1",
        "price": 18.50,
        "url": "test.url",
        "artist_id": 11,
    },
    {
        "name": "Tank Top 2",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 11,
    },
    {
        "name": "T-Shirt 1",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 11,
    },
    {
        "name": "T-Shirt 2",
        "price": 22.50,
        "url": "test.url",
        "artist_id": 11,
    },
    {
        "name": "Hoodie 1",
        "price": 23.50,
        "url": "test.url",
        "artist_id": 11,
    },
    {
        "name": "Hoodie 2",
        "price": 25.00,
        "url": "test.url",
        "artist_id": 11,
    },
    # Demo Artist 12
    {
        "name": "Sticker",
        "price": 1.50,
        "url": "test.url",
        "artist_id": 12,
    },
    {
        "name": "Album 1",
        "price": 9.00,
        "url": "test.url",
        "artist_id": 12,
    },
    {
        "name": "Album 2",
        "price": 10.00,
        "url": "test.url",
        "artist_id": 12,
    },
    {
        "name": "Tank Top 1",
        "price": 18.50,
        "url": "test.url",
        "artist_id": 12,
    },
    {
        "name": "Tank Top 2",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 12,
    },
    {
        "name": "T-Shirt 1",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 12,
    },
    {
        "name": "T-Shirt 2",
        "price": 22.50,
        "url": "test.url",
        "artist_id": 12,
    },
    {
        "name": "Hoodie 1",
        "price": 23.50,
        "url": "test.url",
        "artist_id": 12,
    },
    {
        "name": "Hoodie 2",
        "price": 25.00,
        "url": "test.url",
        "artist_id": 12,
    },
    # Demo Artist 13
    {
        "name": "Sticker",
        "price": 1.50,
        "url": "test.url",
        "artist_id": 13,
    },
    {
        "name": "Album 1",
        "price": 9.00,
        "url": "test.url",
        "artist_id": 13,
    },
    {
        "name": "Album 2",
        "price": 10.00,
        "url": "test.url",
        "artist_id": 13,
    },
    {
        "name": "Tank Top 1",
        "price": 18.50,
        "url": "test.url",
        "artist_id": 13,
    },
    {
        "name": "Tank Top 2",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 13,
    },
    {
        "name": "T-Shirt 1",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 13,
    },
    {
        "name": "T-Shirt 2",
        "price": 22.50,
        "url": "test.url",
        "artist_id": 13,
    },
    {
        "name": "Hoodie 1",
        "price": 23.50,
        "url": "test.url",
        "artist_id": 13,
    },
    {
        "name": "Hoodie 2",
        "price": 25.00,
        "url": "test.url",
        "artist_id": 13,
    },
    # Demo Artist 14
    {
        "name": "Sticker",
        "price": 1.50,
        "url": "test.url",
        "artist_id": 14,
    },
    {
        "name": "Album 1",
        "price": 9.00,
        "url": "test.url",
        "artist_id": 14,
    },
    {
        "name": "Album 2",
        "price": 10.00,
        "url": "test.url",
        "artist_id": 14,
    },
    {
        "name": "Tank Top 1",
        "price": 18.50,
        "url": "test.url",
        "artist_id": 14,
    },
    {
        "name": "Tank Top 2",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 14,
    },
    {
        "name": "T-Shirt 1",
        "price": 20.00,
        "url": "test.url",
        "artist_id": 14,
    },
    {
        "name": "T-Shirt 2",
        "price": 22.50,
        "url": "test.url",
        "artist_id": 14,
    },
    {
        "name": "Hoodie 1",
        "price": 23.50,
        "url": "test.url",
        "artist_id": 14,
    },
    {
        "name": "Hoodie 2",
        "price": 25.00,
        "url": "test.url",
        "artist_id": 14,
    },
]
