from datetime import datetime

shows = [
    # Tour id: 1, Artist id: 1
    {
        'artist_id': 1,
        'tour_id': 1,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Tribal Seeds",
        'datetime': datetime(2025, 1, 1, 20),
    },
    {
        'artist_id': 1,
        'tour_id': 1,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Tribal Seeds",
        'datetime': datetime(2025, 1, 1, 20),
    },
    {
        'artist_id': 1,
        'tour_id': 1,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Tribal Seeds",
        'datetime': datetime(2025, 1, 10, 20),
    },
    {
        'artist_id': 1,
        'tour_id': 1,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Warehouse Live',
        'openers': "Tribal Seeds",
        'datetime': datetime(2025, 1, 11, 20),
    },
    {
        'artist_id': 1,
        'tour_id': 1,
        'city': 'Austin',
        'state': 'TX',
        'venue': "Antone's Nightclub",
        'openers': "Tribal Seeds",
        'datetime': datetime(2025, 1, 18, 20),
    },
    {
        'artist_id': 1,
        'tour_id': 1,
        'city': 'Austin',
        'state': 'TX',
        'venue': 'Moody Center',
        'openers': "Tribal Seeds",
        'datetime': datetime(2025, 1, 19, 20),
    },
    # Tour id: 2, Artist id: 2
    {
        'artist_id': 2,
        'tour_id': 2,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Warehouse Live',
        'openers': "Slightly Stoopid",
        'datetime': datetime(2025, 1, 31, 20),
    },
    {
        'artist_id': 2,
        'tour_id': 2,
        'city': 'New Orleans',
        'state': 'LA',
        'venue': "Howlin' Wolf",
        'openers': "Slightly Stoopid",
        'datetime': datetime(2025, 2, 6, 20),
    },
    {
        'artist_id': 2,
        'tour_id': 2,
        'city': 'New Orleans',
        'state': 'LA',
        'venue': "Howlin' Wolf",
        'openers': "Slightly Stoopid",
        'datetime': datetime(2025, 2, 7, 20),
    },
    {
        'artist_id': 2,
        'tour_id': 2,
        'city': 'New Orleans',
        'state': 'LA',
        'venue': "Howlin' Wolf",
        'openers': "Slightly Stoopid",
        'datetime': datetime(2025, 2, 8, 20),
    },
    {
        'artist_id': 2,
        'tour_id': 2,
        'city': 'Miami',
        'state': 'FL',
        'venue': 'Miami Beach Bandshell',
        'openers': "Bumpin' Uglies, Hirie",
        'datetime': datetime(2025, 2, 15, 20),
    },
    {
        'artist_id': 2,
        'tour_id': 2,
        'city': 'Miami',
        'state': 'FL',
        'venue': 'The Ground Miami',
        'openers': "Bumpin' Uglies, Hirie",
        'datetime': datetime(2025, 2, 18, 20),
    },
    # Tour id: 3, Artist id: 3
    {
        'artist_id': 3,
        'tour_id': 3,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "David Allen Coe",
        'datetime': datetime(2025, 1, 3, 20),
    },
    {
        'artist_id': 3,
        'tour_id': 3,
        'city': 'Nashville',
        'state': 'TN',
        'venue': 'Ryman Auditorium',
        'openers': "David Allen Coe",
        'datetime': datetime(2025, 1, 10, 20),
    },
    {
        'artist_id': 3,
        'tour_id': 3,
        'city': 'Atlanta',
        'state': 'GA',
        'venue': 'Center Stage Theater',
        'openers': "David Allen Coe",
        'datetime': datetime(2025, 1, 17, 20),
    },
    {
        'artist_id': 3,
        'tour_id': 3,
        'city': 'Atlanta',
        'state': 'GA',
        'venue': 'Center Stage Theater',
        'openers': "David Allen Coe",
        'datetime': datetime(2025, 1, 18, 20),
    },
    {
        'artist_id': 3,
        'tour_id': 3,
        'city': 'Greensboro',
        'state': 'NC',
        'venue': 'Greensboro Coliseum',
        'openers': "David Allen Coe",
        'datetime': datetime(2025, 1, 24, 21),
    },
    {
        'artist_id': 3,
        'tour_id': 3,
        'city': 'Greensboro',
        'state': 'NC',
        'venue': 'Greensboro Coliseum',
        'openers': "David Allen Coe",
        'datetime': datetime(2025, 1, 25, 21),
    },
    # Tour id: 4, Artist id: 4
    {
        'artist_id': 4,
        'tour_id': 4,
        'city': 'Los Angeles',
        'state': 'CA',
        'venue': 'Hollywood Bowl',
        'openers': "Ungrateful Deed",
        'datetime': datetime(2025, 6, 6, 20),
    },
    {
        'artist_id': 4,
        'tour_id': 4,
        'city': 'Los Angeles',
        'state': 'CA',
        'venue': 'Hollywood Bowl',
        'openers': "Ungrateful Deed",
        'datetime': datetime(2025, 6, 7, 21),
    },
    {
        'artist_id': 4,
        'tour_id': 4,
        'city': 'Morrison',
        'state': 'CO',
        'venue': 'Red Rocks Amphitheatre',
        'openers': "Ungrateful Deed",
        'datetime': datetime(2025, 6, 13, 20),
    },
    {
        'artist_id': 4,
        'tour_id': 4,
        'city': 'Morrison',
        'state': 'CO',
        'venue': 'Red Rocks Amphitheatre',
        'openers': "Ungrateful Deed",
        'datetime': datetime(2025, 6, 14, 20),
    },
    {
        'artist_id': 4,
        'tour_id': 4,
        'city': 'Nashville',
        'state': 'TN',
        'venue': 'Ryman Auditorium',
        'openers': "Ungrateful Deed",
        'datetime': datetime(2025, 6, 20, 22),
    },
    {
        'artist_id': 4,
        'tour_id': 4,
        'city': 'Nashville',
        'state': 'TN',
        'venue': 'Ryman Auditorium',
        'openers': "Ungrateful Deed",
        'datetime': datetime(2025, 6, 21, 22),
    },
    # Tour id: 5, Artist id: 5
    {
        'artist_id': 5,
        'tour_id': 5,
        'city': 'New York City',
        'state': 'NY',
        'venue': 'Radio City Music Hall',
        'openers': "ABDB",
        'datetime': datetime(2025, 6, 20, 19),
    },
    {
        'artist_id': 5,
        'tour_id': 5,
        'city': 'New York City',
        'state': 'NY',
        'venue': 'Radio City Music Hall',
        'openers': "ABDB",
        'datetime': datetime(2025, 6, 21, 20),
    },
    {
        'artist_id': 5,
        'tour_id': 5,
        'city': 'New York City',
        'state': 'NY',
        'venue': 'Madison Square Garden',
        'openers': "ABDB, White Service",
        'datetime': datetime(2025, 6, 27, 20),
    },
    {
        'artist_id': 5,
        'tour_id': 5,
        'city': 'Minneapolis',
        'state': 'MN',
        'venue': 'First Avenue',
        'openers': "ABDB, White Service",
        'datetime': datetime(2025, 7, 4, 20),
    },
    # Tour id: 6, Artist id: 6
    {
        'artist_id': 6,
        'tour_id': 6,
        'city': 'New York City',
        'state': 'NY',
        'venue': 'Madison Square Garden',
        'openers': "Grillish Hilly",
        'datetime': datetime(2025, 7, 4, 22),
    },
    {
        'artist_id': 6,
        'tour_id': 6,
        'city': 'New York City',
        'state': 'NY',
        'venue': 'Madison Square Garden',
        'openers': "Grillish Hilly",
        'datetime': datetime(2025, 7, 5, 22),
    },
    {
        'artist_id': 6,
        'tour_id': 6,
        'city': 'New York City',
        'state': 'NY',
        'venue': 'Madison Square Garden',
        'openers': "Grillish Hilly",
        'datetime': datetime(2025, 7, 6, 22),
    },
    {
        'artist_id': 6,
        'tour_id': 6,
        'city': 'New York City',
        'state': 'NY',
        'venue': 'Madison Square Garden',
        'openers': "Grillish Hilly",
        'datetime': datetime(2025, 7, 11, 22),
    },
    {
        'artist_id': 6,
        'tour_id': 6,
        'city': 'New York City',
        'state': 'NY',
        'venue': 'Madison Square Garden',
        'openers': "Grillish Hilly",
        'datetime': datetime(2025, 7, 12, 22),
    },
    {
        'artist_id': 6,
        'tour_id': 6,
        'city': 'New York City',
        'state': 'NY',
        'venue': 'Madison Square Garden',
        'openers': "Grillish Hilly",
        'datetime': datetime(2025, 7, 13, 22),
    },
    # Tour id: 7, Artist id: 10
    {
        'artist_id': 7,
        'tour_id': 7,
        'city': 'Las Vegas',
        'state': 'NV',
        'venue': 'Downtown Las Vegas Events Center',
        'openers': "Roombah",
        'datetime': datetime(2025, 7, 4, 20),
    },
    {
        'artist_id': 7,
        'tour_id': 7,
        'city': 'Las Vegas',
        'state': 'NV',
        'venue': 'Hard Rock Cafe',
        'openers': "Roombah",
        'datetime': datetime(2025, 7, 5, 20),
    },
    {
        'artist_id': 7,
        'tour_id': 7,
        'city': 'Las Vegas',
        'state': 'NV',
        'venue': 'Hard Rock Cafe',
        'openers': "Roombah",
        'datetime': datetime(2025, 7, 6, 20),
    },
    {
        'artist_id': 7,
        'tour_id': 7,
        'city': 'Las Vegas',
        'state': 'NV',
        'venue': 'House of Blues',
        'openers': "Roombah",
        'datetime': datetime(2025, 7, 11, 20),
    },
    {
        'artist_id': 7,
        'tour_id': 7,
        'city': 'Las Vegas',
        'state': 'NV',
        'venue': 'House of Blues',
        'openers': "Roombah",
        'datetime': datetime(2025, 7, 12, 20),
    },
    {
        'artist_id': 7,
        'tour_id': 7,
        'city': 'Las Vegas',
        'state': 'NV',
        'venue': 'Downtown Las Vegas Events Center',
        'openers': "Roombah",
        'datetime': datetime(2025, 7, 18, 20),
    },
    # Tour id: 8, Artist id: 8
    {
        'artist_id': 8,
        'tour_id': 8,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "LunaBella",
        'datetime': datetime(2025, 7, 4, 21),
    },
    {
        'artist_id': 8,
        'tour_id': 8,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Wiccan",
        'datetime': datetime(2025, 7, 11, 22),
    },
    {
        'artist_id': 8,
        'tour_id': 8,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Wiccan",
        'datetime': datetime(2025, 7, 12, 22),
    },
    {
        'artist_id': 8,
        'tour_id': 8,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Warehouse Live',
        'openers': "Poochie!",
        'datetime': datetime(2025, 7, 18, 21),
    },
    {
        'artist_id': 8,
        'tour_id': 8,
        'city': 'Austin',
        'state': 'TX',
        'venue': "Antone's Nightclub",
        'openers': "Poochie!",
        'datetime': datetime(2025, 7, 19, 21),
    },
    {
        'artist_id': 8,
        'tour_id': 8,
        'city': 'Austin',
        'state': 'TX',
        'venue': 'Moody Center',
        'openers': "Poochie!",
        'datetime': datetime(2025, 7, 25, 22),
    },
    # Tour id: 9, Artist id: 12
    {
        'artist_id': 9,
        'tour_id': 9,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Navila",
        'datetime': datetime(2025, 7, 5, 21),
    },
    {
        'artist_id': 9,
        'tour_id': 9,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Warehouse Live',
        'openers': "Ned Flanders Band",
        'datetime': datetime(2025, 7, 11, 21),
    },
    {
        'artist_id': 9,
        'tour_id': 9,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Warehouse Live',
        'openers': "Ned Flanders Band",
        'datetime': datetime(2025, 7, 12, 21),
    },
    {
        'artist_id': 9,
        'tour_id': 9,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Fitzgeralds',
        'openers': "Ned Flanders Band",
        'datetime': datetime(2025, 7, 18, 21),
    },
    {
        'artist_id': 9,
        'tour_id': 9,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Fitzgeralds',
        'openers': "Ned Flanders Band",
        'datetime': datetime(2025, 7, 19, 21),
    },
    {
        'artist_id': 9,
        'tour_id': 9,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Ned Flanders Band",
        'datetime': datetime(2025, 7, 25, 21),
    },
    # Tour id: 10, Artist id: 10
    {
        'artist_id': 10,
        'tour_id': 10,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Mangled Digits",
        'datetime': datetime(2025, 7, 18, 21),
    },
    {
        'artist_id': 10,
        'tour_id': 10,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Mangled Digits",
        'datetime': datetime(2025, 7, 19, 21),
    },
    {
        'artist_id': 10,
        'tour_id': 10,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Mangled Digits",
        'datetime': datetime(2025, 7, 20, 21),
    },
    {
        'artist_id': 10,
        'tour_id': 10,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Demo Rock",
        'datetime': datetime(2025, 7, 25, 21),
    },
    {
        'artist_id': 10,
        'tour_id': 10,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Demo Rock",
        'datetime': datetime(2025, 7, 26, 21),
    },
    {
        'artist_id': 10,
        'tour_id': 10,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'House of Blues',
        'openers': "Demo Rock",
        'datetime': datetime(2025, 7, 27, 21),
    },
    # Tour id: 11, Artist id: 11
    {
        'artist_id': 11,
        'tour_id': 11,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Fitzgeralds',
        'openers': "Iambik",
        'datetime': datetime(2025, 7, 4, 21),
    },
    {
        'artist_id': 11,
        'tour_id': 11,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Fitzgeralds',
        'openers': "Iambik",
        'datetime': datetime(2025, 7, 5, 21),
    },
    {
        'artist_id': 11,
        'tour_id': 11,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Fitzgeralds',
        'openers': "Iambik",
        'datetime': datetime(2025, 7, 24, 21),
    },
    {
        'artist_id': 11,
        'tour_id': 11,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Fitzgeralds',
        'openers': "Iambik",
        'datetime': datetime(2025, 7, 25, 21),
    },
    {
        'artist_id': 11,
        'tour_id': 11,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Fitzgeralds',
        'openers': "Iambik",
        'datetime': datetime(2025, 7, 26, 21),
    },
    {
        'artist_id': 11,
        'tour_id': 11,
        'city': 'Houston',
        'state': 'TX',
        'venue': 'Fitzgeralds',
        'openers': "Iambik",
        'datetime': datetime(2025, 7, 27, 21),
    },

]
