users = [
    {
        'id': 1,
        'username': 'Demo',
        'email': 'demo@aa.io',
        'password': 'password',
        'is_artist': True,
    },
    {
        'id': 2,
        'username': 'marnie',
        'email': 'marnie@aa.io',
        'password': 'password',
        'is_artist': True,
    },
    {
        'id': 3,
        'username': 'bobby',
        'email': 'bobby@aa.io',
        'password': 'password',
        'is_artist': True,
    },
    {
        'id': 4,
        'username': 'darrel',
        'email': 'darrel@aa.io',
        'password': 'password',
        'is_artist': False,
    },
    {
        'id': 5,
        'username': 'Jina',
        'email': 'Jinyaa@google.io',
        'password': 'password',
        'is_artist': False,
    },
    {
        'id': 6,
        'username': 'ricky',
        'email': 'ricky@aa.io',
        'password': 'password',
        'is_artist': True,
    },
    {
        'id': 7,
        'username': 'purple-paper',
        'email': 'purp.pap@pp.io',
        'password': 'password',
        'is_artist': True,
    },
    {
        'id': 8,
        'username': 'music-lover1994',
        'email': 'iheartmus1c!@google.io',
        'password': 'password',
        'is_artist': False,
        'artist_name': None
    },
    {
        'id': 9,
        'username': 'Jonnie Cache',
        'email': 'jc@jcp.co',
        'password': 'password',
        'is_artist': True,
    },
    {
        'id': 10,
        'username': 'gtrLegend_59',
        'email': 'ghero24@hotmail.com',
        'password': 'password',
        'is_artist': True,
    },
    {
        'id': 11,
        'username': 'Navila',
        'email': 'nvsal@hotmail.com',
        'password': 'password',
        'is_artist': True,
    },
    {
        'id': 12,
        'username': 'LunaBella',
        'email': 'luna@gmail.com',
        'password': 'password',
        'is_artist': True,
    },
    {
        'id': 13,
        'username': 'Anachronism',
        'email': 'AMP@gmail.com',
        'password': 'password',
        'is_artist': True,
    },
    {
        'id': 14,
        'username': 'manager',
        'email': 'manager@md.com',
        'password': 'password',
        'is_artist': True,
    },
]
