"""empty message

Revision ID: f204381557e8
Revises: ffdc0a98111c
Create Date: 2024-11-21 02:03:29.573194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f204381557e8'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageable_type', sa.String(), nullable=False),
    sa.Column('imageable_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_artist', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('artist_name', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('artist_name')
        batch_op.drop_column('is_artist')

    op.drop_table('images')
    # ### end Alembic commands ###
