"""add votable table and vote seeds

Revision ID: 701fad976597
Revises: 203fc207c99c
Create Date: 2025-06-05 19:20:28.383094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '701fad976597'
down_revision = '203fc207c99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votable_id', sa.Integer(), nullable=False),
    sa.Column('votable_type', postgresql.ENUM('post', 'comment', name='votable_types'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('votable_id', 'votable_type', 'user_id', name='unique_vote_per_user')
    )
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_comment_per_user_per_post', ['user_id', 'post_id'])

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('unique_comment_per_user_per_post', type_='unique')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.drop_table('votes')
    # ### end Alembic commands ###
