"""add posts and comments tables

Revision ID: 203fc207c99c
Revises: 99f0977e3e9e
Create Date: 2025-06-05 03:39:31.516798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203fc207c99c'
down_revision = '99f0977e3e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(length=400), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=400), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_pics', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_user", ['user_id']) # type: ignore

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_pics', schema=None) as batch_op:
        batch_op.drop_constraint("unique_user", type_='unique') # type: ignore

    op.drop_table('comments')
    op.drop_table('posts')
    # ### end Alembic commands ###
